name: Auto-format C code (Google Style)

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allows the action to push commits to the PR branch

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Run clang-format (Google style)
        run: |
          find . -type f \( -name "*.c" -o -name "*.h" \) \
            -exec clang-format -i --style=Google {} +

      - name: Commit and push formatting changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "ci(format): auto-apply clang-format (Google style)"
            git push
          else
            echo "No formatting changes detected."
          fi
